# Site settings
description: Eduserv Technical Blog Test
baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog
url: "http://willianjusten.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
encoding: utf-8

# User settings
username: A Test Eduserv Technical Blog in Jekyll
user_description: Technical information
user_title: Steve Newstead
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
    
 # Author details.
sna:
    name: Steve Newstead
    email: steve@steve.com
    web: http://twitter.com/mangopieface

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
